services:
  app:
    image: noozecrypt/quick-chat-backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quick-chat-db
      SPRING_DATASOURCE_USERNAME: quick-chat
      SPRING_DATASOURCE_PASSWORD: quick-chat
      KEYCLOAK_URL: http://host.docker.internal:8070/realms/quick-chat
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quick-chat-db
      POSTGRES_USER: quick-chat
      POSTGRES_PASSWORD: quick-chat
    ports:
      - 5432:5432